apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: uidcw77v0-nodejs 
  janus-idp.io/tekton: uidcw77v0-nodejs
  backstage.io/kubernetes-id: uidcw77v0-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uidcw77v0-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml